### ISSUE TITLE
register.ejs cannot post new user

### ISSUE THREAD

**Issue by Manwej** [Manwej/Journal.MERN#1]
register.ejs

gets me

UnhandledPromiseRejectionWarning: ValidationError: User validation failed: name: Path `name` is required., email: Path `email` is required., password: Path `password` is required.
    at new ValidationError (/Users/ioanamitrea/Desktop/Ubiqum/Journal/server/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/Users/ioanamitrea/Desktop/Ubiqum/Journal/server/node_modules/mongoose/lib/document.js:2563:32)
    at /Users/ioanamitrea/Desktop/Ubiqum/Journal/server/node_modules/mongoose/lib/document.js:2385:17
    at /Users/ioanamitrea/Desktop/Ubiqum/Journal/server/node_modules/mongoose/lib/schematype.js:1181:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by Manwej** [comment]
@stephane-tatin solved it
